services:
        service:
                ports:
                - "8080:8080"
                links:
                - "db"
                depends_on:
                - db
                environment:
                - DATABASE_HOST=db
        db:
                ports:
                - "3306:3306"
                build: /var/lib/mysql
                environment:
                - MYSQL_ROOT_PASSWORD=123456